### ISSUE TITLE
auto renew-subscription

### ISSUE THREAD

**Issue by user723** [smokelaboratory/easy-iap#1]
When I purchase a non-consumable product (Subscription) with tester account, everythings work perfectly. After purchase I can get “order ID, status, etc… But when monthly subscription renews after 5 minutes (or yearly subscription after 30 minutes as a tester), I don’t get old or renew purchase information, so I get the result as not purchased. How to get subscription information, when it renews?

**Comment by smokelaboratory** [comment]
Hi @user723. This library returns a list of available products. When you purchase an already subscribed product, Google will throw an error stating that the product is already purchased. If you want to know the status of your product, you can have that feature configured at server-side using Google's APIs.
https://docs.huihoo.com/android/4.4/google/play/billing/gp-purchase-status-api.html

If this is not what you are looking for, please elaborate your issue along with library output and logs if available,

**Comment by user723** [comment]
When I purchase first subscription product, I can get the status of subscription product until the subscription renews automatically. After renew subscription, I don't get any product status anymore.

**Comment by smokelaboratory** [comment]
You shouldn't rely on billing API delegates to manage the current state of purchased products. This issue can also be observed in [Android's in-app demo](https://github.com/android/play-billing-samples). Server-side in-app integration will help you along with other features like cancelation notification and much more.

Closing this as it is Google billing API issue.
